import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import * as api from "../../services/api";
import ConfirmDialog from "../ConfirmDialog/ConfirmDialog";
import "./ProductReviews.css";
import "./ReviewModerationStatus.css";

const Stars = ({ value, interactive, onChange }) => <span className={`review-stars ${interactive ? "interactive" : ""}`} aria-label={`${value} out of 5 stars`}>{[1,2,3,4,5].map((star) => interactive ? <button key={star} type="button" aria-label={`${star} stars`} className={star <= value ? "filled" : ""} onClick={() => onChange(star)}>★</button> : <span key={star} className={star <= value ? "filled" : ""}>★</span>)}</span>;
const variantLabel = (value) => value?.variantName || value?.variantSku || value?.sku || "Original variant";

export default function ProductReviews({ productId }) {
  const { accessToken, isAuthenticated, isAdmin } = useAuth(); const location = useLocation();
  const [reviews,setReviews]=useState([]), [mine,setMine]=useState([]), [reviewable,setReviewable]=useState([]), [selectedOrderItemId,setSelectedOrderItemId]=useState(""), [rating,setRating]=useState(5), [reviewText,setReviewText]=useState(""), [editing,setEditing]=useState(null), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState(""), [notice,setNotice]=useState(""), [deleting,setDeleting]=useState(null), [dialogBusy,setDialogBusy]=useState(false), [dialogError,setDialogError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const customer=isAuthenticated&&!isAdmin;const [page,myReviews,eligible]=await Promise.all([api.getProductReviews(productId),customer?api.getMyProductReview(accessToken,productId):[],customer?api.getReviewableVariants(accessToken,productId):[]]);setReviews(page.content||[]);setMine(myReviews||[]);setReviewable(eligible||[]);setSelectedOrderItemId((eligible||[])[0]?.orderItemId||"");}catch(e){setError(e.message);}finally{setLoading(false);}},[accessToken,isAdmin,isAuthenticated,productId]);
  useEffect(()=>{load();},[load]);
  const average=useMemo(()=>reviews.length?reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length:0,[reviews]);
  const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");setNotice("");try{if(editing){await api.updateReview(accessToken,editing.reviewId,{rating,reviewText});}else{await api.createReview(accessToken,{productId:Number(productId),orderItemId:Number(selectedOrderItemId),rating,reviewText});}setEditing(null);setRating(5);setReviewText("");setNotice(editing?"Your review has been updated and is live.":"Thank you. Your review is now live for every shopper.");await load();}catch(err){setError(err.message);}finally{setSaving(false);}};
  const confirmRemove=async()=>{setDialogError("");setDialogBusy(true);try{await api.deleteReview(accessToken,deleting.reviewId);setDeleting(null);setNotice("Your review was deleted.");await load();}catch(e){setDialogError(e.message);}finally{setDialogBusy(false);}};
  const edit=(review)=>{setRating(review.rating);setReviewText(review.reviewText||"");setEditing(review);setError("");};
  return <section className="product-reviews" id="reviews"><div className="reviews-heading"><div><span>Customer perspective</span><h2>Variant reviews</h2></div><div className="reviews-score"><strong>{reviews.length?average.toFixed(1):"—"}</strong><div><Stars value={Math.round(average)}/><small>{reviews.length} verified {reviews.length===1?"review":"reviews"}</small></div></div></div>
    {error&&<div className="reviews-alert error" role="alert">{error}</div>}{notice&&<div className="reviews-alert success">{notice}</div>}
    {!isAuthenticated?<div className="review-callout"><h3>Purchased this frame?</h3><p>Sign in to review a specific variant after delivery.</p><Link to="/signin" state={{from:location}}>Sign in to review</Link></div>:isAdmin?<div className="review-callout"><p>Administrator accounts cannot publish customer reviews.</p></div>:<>
      {mine.map(review=><div className="my-review" key={review.reviewId}><div><span>Your review · {variantLabel(review)}</span><Stars value={review.rating}/><em className={`my-review-status ${review.reviewStatus.toLowerCase()}`}>{review.reviewStatus}</em></div><p>{review.reviewText||"Rating only"}</p>{review.reviewStatus==="PENDING"&&<small>Being re-checked after moderation. It is not public at the moment.</small>}{review.reviewStatus==="REJECTED"&&<small>This review was removed by moderation and is not public. Editing it sends it back for review.</small>}<div><button onClick={()=>edit(review)}>Edit review</button><button className="delete" onClick={()=>{setDialogError("");setDeleting(review);}}>Delete</button></div></div>)}
      {(editing||reviewable.length>0)?<form className="review-form" onSubmit={submit}>{!editing&&<label>Purchased variant<select required value={selectedOrderItemId} onChange={e=>setSelectedOrderItemId(e.target.value)}>{reviewable.map(item=><option key={item.orderItemId} value={item.orderItemId}>{variantLabel(item)}{item.variantName&&item.sku?` · ${item.sku}`:""}</option>)}</select></label>}{editing&&<strong className="editing-variant">Editing: {variantLabel(editing)}</strong>}<div><label>Your rating</label><Stars value={rating} interactive onChange={setRating}/></div><label>Review <span>Optional</span><textarea value={reviewText} onChange={e=>setReviewText(e.target.value)} maxLength="2000" rows="4" placeholder="How did this specific color and variant look, feel and fit?"/></label><div className="review-form-footer"><small>Only delivered variants can be reviewed.</small>{editing&&<button type="button" className="cancel" onClick={()=>{setEditing(null);setRating(5);setReviewText("");}}>Cancel</button>}<button disabled={saving||(!editing&&!selectedOrderItemId)}>{saving?"Saving…":editing?"Update variant review":"Publish variant review"}</button></div></form>:mine.length>0&&<div className="review-callout"><p>You have reviewed every delivered variant of this product.</p></div>}
    </>}
    <div className="reviews-list">{loading?<p className="reviews-empty">Loading reviews…</p>:reviews.length===0?<p className="reviews-empty">No reviews yet. Be the first verified customer to share your view.</p>:reviews.map(review=><article key={review.reviewId}><div className="review-avatar">{review.customerName?.charAt(0).toUpperCase()}</div><div><header><strong>{review.customerName}</strong><span>Verified · {variantLabel(review)}</span><time>{new Date(review.createdAt).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</time></header><Stars value={review.rating}/><p>{review.reviewText||"Rating only"}</p></div></article>)}</div>
    <ConfirmDialog open={Boolean(deleting)} title="Delete your review?"
      confirmLabel="Delete review" cancelLabel="Keep review" busyLabel="Deleting…"
      busy={dialogBusy} error={dialogError}
      onCancel={()=>{setDeleting(null);setDialogError("");}} onConfirm={confirmRemove}>
      <p>Your review of <strong>{variantLabel(deleting)}</strong> will be removed for good. You can write a new one for this variant afterwards.</p>
    </ConfirmDialog></section>;
}
