import { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "../../context/AuthContext";
import { getAdminCustomers, getAdminOrders, getAdminProducts, getAdminReturns, getEmailOutboxSummary } from "../../services/api";
import "./AdminOverview.css";

const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits:0 })}`;
const date = (value) => value ? new Date(value).toLocaleString("en-IN", { dateStyle:"medium", timeStyle:"short" }) : "—";
const activeReturnStatuses = ["REQUESTED","APPROVED","PICKED_UP","RECEIVED"];
const offerActive = (coupon) => coupon.isActive && new Date(coupon.validFrom) <= new Date() && new Date(coupon.validTo) >= new Date();

export default function AdminOverview({ coupons, offersLoading, onNavigate, onNewOffer }) {
  const { accessToken } = useAuth();
  const [data,setData]=useState({orders:[],products:[],customers:0,returns:[],email:{pending:0,retry:0,failed:0,sent:0,total:0}});
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [updatedAt,setUpdatedAt]=useState(null);
  const load=useCallback(async()=>{setLoading(true);setError("");const results=await Promise.allSettled([getAdminOrders(accessToken),getAdminProducts(accessToken),getAdminCustomers(accessToken),getAdminReturns(accessToken),getEmailOutboxSummary(accessToken)]);const failed=results.filter((item)=>item.status==="rejected");setData((current)=>({orders:results[0].status==="fulfilled"?(results[0].value.content||[]):current.orders,products:results[1].status==="fulfilled"?(results[1].value.content||[]):current.products,customers:results[2].status==="fulfilled"?(results[2].value.totalElements||results[2].value.content?.length||0):current.customers,returns:results[3].status==="fulfilled"?(results[3].value.content||[]):current.returns,email:results[4].status==="fulfilled"?results[4].value:current.email}));if(failed.length)setError(`${failed.length} dashboard data source${failed.length===1?"":"s"} could not be refreshed.`);setUpdatedAt(new Date());setLoading(false)},[accessToken]);
  useEffect(()=>{load()},[load]);
  const metrics=useMemo(()=>{const variants=data.products.flatMap((product)=>(product.variants||[]).map((variant)=>({...variant,productActive:product.isActive})));const activeVariants=variants.filter((variant)=>variant.productActive&&variant.isActive);return{gross:data.orders.filter((order)=>order.orderStatus!=="CANCELLED").reduce((sum,order)=>sum+Number(order.totalAmount),0),needsAction:data.orders.filter((order)=>["PLACED","CONFIRMED"].includes(order.orderStatus)).length,activeProducts:data.products.filter((product)=>product.isActive).length,units:activeVariants.reduce((sum,variant)=>sum+Number(variant.quantityAvailable),0),low:activeVariants.filter((variant)=>variant.quantityAvailable>0&&variant.quantityAvailable<=variant.lowStockThreshold).length,out:activeVariants.filter((variant)=>variant.quantityAvailable===0).length,activeReturns:data.returns.filter((item)=>activeReturnStatuses.includes(item.returnStatus)).length}},[data]);
  const statuses=useMemo(()=>["PLACED","CONFIRMED","PROCESSING","SHIPPED","DELIVERED"].map((status)=>({status,count:data.orders.filter((order)=>order.orderStatus===status).length})),[data.orders]);
  const maxStatus=Math.max(1,...statuses.map((item)=>item.count));
  const recent=[...data.orders].sort((a,b)=>new Date(b.purchasedAt)-new Date(a.purchasedAt)).slice(0,6);
  const attention=[{section:"orders",tone:"urgent",count:metrics.needsAction,title:"Orders need action",copy:"Placed or confirmed orders waiting for fulfillment."},{section:"inventory",tone:metrics.out?"urgent":"warning",count:metrics.out,title:"SKUs out of stock",copy:`${metrics.low} additional SKU${metrics.low===1?" is":"s are"} below its alert threshold.`},{section:"returns",tone:"warning",count:metrics.activeReturns,title:"Open returns",copy:"Requests moving through review, pickup or inspection."},{section:"email-outbox",tone:data.email.failed?"urgent":"neutral",count:data.email.failed,title:"Failed emails",copy:`${data.email.pending+data.email.retry} message${data.email.pending+data.email.retry===1?"":"s"} waiting or retrying.`}];

  return <section className="overview-dashboard">{error&&<div className="admin-alert error">{error}</div>}<div className="overview-welcome"><div><span>Command centre</span><h2>Your store, at a glance.</h2><p>Live operational signals from orders, stock, customers and service workflows.</p></div><div><small>{updatedAt ? `Updated ${updatedAt.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}` : "—"}</small><button onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh dashboard"}</button></div></div>
    <div className="overview-kpis"><article><span>Gross order value</span><strong>{loading?"—":money(metrics.gross)}</strong><small>Across {data.orders.length} loaded orders</small></article><article><span>Orders needing action</span><strong>{loading?"—":metrics.needsAction}</strong><button onClick={()=>onNavigate("orders")}>Open orders →</button></article><article><span>Active products</span><strong>{loading?"—":metrics.activeProducts}</strong><small>{metrics.units.toLocaleString("en-IN")} sellable units</small></article><article><span>Customers</span><strong>{loading?"—":data.customers}</strong><button onClick={()=>onNavigate("customers")}>View directory →</button></article><article><span>Active offers</span><strong>{offersLoading?"—":coupons.filter(offerActive).length}</strong><button onClick={()=>onNavigate("offers")}>Manage offers →</button></article></div>
    <div className="overview-grid"><section className="overview-card attention-card"><header><div><span>Attention queue</span><h3>What needs you now</h3></div></header><div>{attention.map((item)=><button key={item.section} onClick={()=>onNavigate(item.section)}><em className={item.tone}>{item.count}</em><span><strong>{item.title}</strong><small>{item.copy}</small></span><b>→</b></button>)}</div></section>
      <section className="overview-card fulfillment-card"><header><div><span>Fulfillment</span><h3>Order pipeline</h3></div><button onClick={()=>onNavigate("orders")}>View all</button></header><div>{statuses.map((item)=><div key={item.status}><span>{item.status.replaceAll("_"," ")}</span><i><b style={{width:`${item.count/maxStatus*100}%`}}/></i><strong>{item.count}</strong></div>)}</div></section></div>
    <section className="overview-card recent-card"><header><div><span>Recent activity</span><h3>Latest orders</h3></div><button onClick={()=>onNavigate("orders")}>All orders</button></header>{recent.length===0?<p className="overview-empty">No orders have been placed yet.</p>:<div className="recent-orders"><div className="recent-head"><span>Order</span><span>Customer</span><span>Placed</span><span>Total</span><span>Status</span></div>{recent.map((order)=><button key={order.orderId} onClick={()=>onNavigate("orders")}><strong>#{order.orderId}</strong><span>{order.customer?.name}<small>{order.customer?.email}</small></span><span>{date(order.purchasedAt)}</span><strong>{money(order.totalAmount)}</strong><em className={`order-badge ${order.orderStatus.toLowerCase()}`}>{order.orderStatus}</em></button>)}</div>}</section>
    <section className="overview-actions"><div><span>Quick actions</span><h3>Keep the store moving</h3></div><button onClick={()=>onNavigate("products")}>Manage products</button><button onClick={onNewOffer}>+ Create offer</button><button onClick={()=>onNavigate("inventory")}>Receive stock</button><button onClick={()=>onNavigate("email-outbox")}>Check email delivery</button></section>
  </section>;
}
